// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  eyebrow?: string;
  lead?: string;
  hero_cta_label?: string;
  hero_cta_url?: string;
  microcopy?: string;
  content?: PortableTextBlock[];
  show_cta_band?: boolean;
  hero_eyebrow?: string;
  hero_headline_before?: string;
  hero_headline_accent?: string;
  hero_lead_strong?: string;
  hero_lead_rest?: string;
  hero_primary_cta?: string;
  hero_secondary_cta?: string;
  hero_badge_1?: string;
  hero_badge_2?: string;
  hero_badge_3?: string;
  hero_disclaimer?: string;
  wwd_eyebrow?: string;
  wwd_title?: string;
  wwd_body?: string;
  eco_eyebrow?: string;
  eco_title?: string;
  eco_body?: string;
  proc_eyebrow?: string;
  proc_title?: string;
  proc_body?: string;
  uw_eyebrow?: string;
  uw_title?: string;
  uw_body?: string;
  rm_eyebrow?: string;
  rm_title?: string;
  rm_body?: string;
  lead_eyebrow?: string;
  lead_title?: string;
  lead_body?: string;
  lead_kicker?: string;
  lead_name?: string;
  lead_role?: string;
  lead_stat1_title?: string;
  lead_stat1_body?: string;
  lead_stat2_title?: string;
  lead_stat2_body?: string;
  lead_cta?: string;
  cta_eyebrow?: string;
  cta_title?: string;
  cta_body?: string;
  cta_button?: string;
  hero?: unknown;
  what_we_do?: unknown;
  ecosystem?: unknown;
  process?: unknown;
  underwriting?: unknown;
  roadmap?: unknown;
  leadership?: unknown;
  cta_band?: unknown;
  sections?: unknown;
  notice?: string;
  contact?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  excerpt?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    posts: Post;
  }
}